### PR TITLE
team EDA

### PR DESCRIPTION
**Pull request by monicafar147**
Keane and Syiasanga push their work into this pull request.
Once the work is reviewed and approved, Monica will merge the pull request.
Your EDA work here will overwrite the EDA work done in the development branch.

### CODE REVIEW

**Comment by monicafar147** [comment]
image
image

Cool word clouds!

- What is interesting is that in the sentiment -1 cloud, the word science pops up
- Also in the -1 cloud there are references to the chinese? 
- who is Stephen Schlegel? he was referenced in the 1 sentiment
- who is Steves Goddard? he was referenced in the -1 sentiment
- politicians in the -1 sentiment include Al Gore, Obama, real Donald trump
- politicians in the +1 sentiment include Bernie Sanders, Trump

**Comment by Keane257** [comment]
Yeah ill put that in the notes doc in the drive folder
also added basic some more basic eda

Hashtags:
image

@'s
image

RT vs OP
image

**Comment by Keane257** [comment]
No idea who Steve Goddard is this is all i could find 🤔 

 In 2004, 30-year beauty industry veteran Steve Goddard launched PRAVANA, a global salon professional hair care brand "created by stylists, for stylists.” Goddard has always had a passion for making a difference through philanthropy

same with Stephen Schlegel no-idea

**Comment by monicafar147** [comment]
I like the hashtags frequency EDA! well done

**Comment by Keane257** [comment]
Thanks! still trying to extract insights from that

**Comment by monicafar147** [comment]
I added the same EDA for the neutral and news tweets too

**Comment by Keane257** [comment]
Nice looks good, the addition of neutral and factual tweets adds even more 
So yeah looks good and ready to merge!

**Pull request merged**
