### PR TITLE
Added text preprocessing and EDA

### PR DESCRIPTION
**Pull request by monicafar147**

### CODE REVIEW

**Comment by monicafar147** [comment]
image

**Comment by monicafar147** [comment]
image

**Comment by monicafar147** [comment]
image

**Comment by monicafar147** [comment]
These distributions were done before the text cleaning process. It will be interesting to see the distributions after text cleaning happened :)

**Comment by monicafar147** [comment]
The output after cleaning the text
image

**Comment by monicafar147** [comment]
- [x]  Need to fix URL (http:\\link -> URL)
- [x]  Need to make one preprocessing function
- [x]  Analyse train and text data after preprocessing

**Comment by monicafar147** [comment]
EDA after preprocessing
image

**Comment by monicafar147** [comment]
Testing data:
image

**Comment by monicafar147** [comment]
word count for train data:
image

**Comment by monicafar147** [comment]
word count for testing data:
image

**Comment by monicafar147** [comment]
output afer preprocessing
1: polyscimajor epa chief think carbon dioxide main because global warming and wait what 


2: like lack evidence anthropogenic global warming


3: rt  researchers say three years act climate change it is late 


4:  wired  2016 pivotal year war climate change 


5: rt  2016 racist sexist climate change denying bigot leading polls 


6: worth read whether believe climate change 


7: rt  mike pence does not believe global warming smoking causes lung cancer 


8: rt  six big things today fight climate change climate activistã¢â‚¬â¦ 


9:  8yo nephew inconsolable wants die old age like me perish fiery hellscape climate change


10: rt  offense… like… believe… global warming………

**Review by Keane257 — APPROVED** [review]
Ok coo, thanks

**Pull request merged**
