### PR TITLE
made a framework for API devs to work on in base_app.py

### PR DESCRIPTION
**Pull request by monicafar147**
- [x] add preprocess function in app
- [x] add pickled file to our repository
- [x] test app
- [ ] add more models
- [ ] add EDA
- [ ] add research

### CODE REVIEW

**Comment by monicafar147** [comment]
used the following preprocessing for now:
image

**Comment by monicafar147** [comment]
used the following model that Siyasanga proposed:
image

**Comment by monicafar147** [comment]
pickled the model and saved it under resources folder:
image

**Comment by monicafar147** [comment]
loaded the pickled model succesfully:
image

**Comment by monicafar147** [comment]
tested the pickled file on unseen test data:
image

**Comment by monicafar147** [comment]
got the following report result:
image

**Comment by Keane257** [comment]
OK nice looking good so far!

**Comment by monicafar147** [comment]
@Keane257 this is how the test data looks after preprocessing
image

**Comment by monicafar147** [comment]
This is the output of the API so far
image

**Comment by monicafar147** [comment]
maybe we should remove the 'http', 'www' and 'com' words and only focus on the inner URL?
image

**Comment by monicafar147** [comment]
at the moment our app is clasifying words and not a sentence
image

**Review by Keane257 — COMMENTED** [review]
Ok yeah i see i think it would be beneficial to only focus on inner tweet however i'm jot sure why its classifying each word instead of the sentence we i'm going to have to look at the code for that. But so far we've got something so well done on that

**Comment by Keane257** [comment]
Ok cool got it to work, just added a random new button to test it out

**Comment by monicafar147** [comment]
our base API works - will close this pull request and open a new branch for the API

**Pull request closed without merging**
