### PR TITLE
Made a template for the preprocessing team to use

### PR DESCRIPTION
**Pull request by monicafar147**
Push changes to this pull request.
Ask team lead to review changes.
Team lead will inform Monica to merge.

### CODE REVIEW

**Comment by Keane257** [comment]
So in the climate_change.pynb file there is a couple errors:
add " ! " to pip install so it should be !pip install:
Also move the nltk.download('stopword') to after the imports so that it can import the libary before downloading cause it gives an error:

I can change these but wasn't sure if i should just rather say it here and either Zizipho or Khanyisa push, that way its quite ordered, but i don't mind?

**Review by Keane257 — COMMENTED** [review]
Sorry i didn't see the review option same thing i commented though:
So in the climate_change.pynb file there is a couple errors:
add " ! " to pip install so it should be !pip install:
Also move the nltk.download('stopword') to after the imports so that it can import the libary before downloading cause it gives an error:

I can change these but wasn't sure if i should just rather say it here and either Zizipho or Khanyisa push, that way its quite ordered, but i don't mind?

**Comment by monicafar147** [comment]
suggestion:
```
def _preprocess(tweet):
    stopwords_list = set(stopwords.words('english') + list(punctuation) + ['AT_USER','URL'])
    tweet = tweet.lower() # convert text to lower-case
    tweet = re.sub('((www\.[^\s]+)|(https?://[^\s]+))', 'URL', tweet) # remove URLs
    tweet = re.sub(r"\W", " ", tweet) # remove usernames
    tweet = re.sub(r'#([^\s]+)', r'\1', tweet) # remove the # in #hashtag
    tweet = word_tokenize(tweet) # remove repeated characters (helloooooooo into hello)
    tweets = [word for word in tweet if word not in stopwords_list]
    return " ".join(tweets) 
```
```
    # load in data
    print('loading in data')
    train = pd.read_csv('https://raw.githubusercontent.com/monicafar147/classification-predict-streamlit-template/master/climate-change-belief-analysis/train.csv')
    print(train.head())
    train['processed'] = train['message'].apply(_preprocess)
    print('data preprocessed')
    #print(train.head())
```

**Comment by monicafar147** [comment]
if you want to keep username and URL then change stopwords_list to
`    stopwords_list = set(stopwords.words('english') + list(punctuation)`

**Comment by monicafar147** [comment]
this preprocess function:
image
following parameters in preprocessing:
image
had the following score:
image

**Comment by monicafar147** [comment]
this preprocess function:
image
following parameters in preprocessing:
had the following score:
image

image

**Comment by monicafar147** [comment]
this preprocess function:
image
following parameters in preprocessing:
image
had the following score:
image

**Comment by monicafar147** [comment]
this preprocess function:
image
following parameters in preprocessing:
image
had the following score:
image

**Comment by Keane257** [comment]
Wow ok brilliant so i think we just stick with that preprocess function and the linearSVC model, cause that model gives the best results no matter the preprocessing. we can look into getting that final notebook.
Those last two look very similar in output

**Comment by Keane257** [comment]
the difference being the URL?

**Comment by monicafar147** [comment]
sorry I pasted the wrong output - the last one is the one Zizipho sent in the final preprocessing notebook

**Comment by monicafar147** [comment]
taking a URL of the format http://fakenews.com 
splitting it up into 'http fakenews com' gives the best output

**Pull request merged**
